# Generated by Django 3.2 on 2022-03-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_source',
        ),
    ]
