# Generated by Django 3.2 on 2022-03-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220326_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
