# Generated by Django 3.2 on 2022-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
