# Generated by Django 3.2 on 2022-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220405_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_time_ago',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
