# Generated by Django 3.2 on 2022-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220422_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, choices=[('in stock', 'In stock'), ('out of stock', 'Out of stock'), ('returning soon', 'Returning soon')], default='out of stock', max_length=100, null=True),
        ),
    ]
