# Generated by Django 3.2 on 2022-04-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220423_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
