# Generated by Django 3.2 on 2022-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220424_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rare',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
