# Generated by Django 3.2 on 2022-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20220426_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='plant_category',
            field=models.CharField(blank=True, choices=[('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PlantCategory',
        ),
    ]
