# Generated by Django 3.2 on 2022-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20220430_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plant_category',
            field=models.CharField(blank=True, choices=[('Potted', 'potted'), ('Hanging', 'hanging'), ('Floor', 'floor'), ('Flowers', 'flowers'), ('Succulents', 'succulents')], max_length=30, null=True),
        ),
    ]
