# Generated by Django 3.2 on 2022-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20220509_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
